src/app/models.py
from datetime import datetime

from flask_login import UserMixin
from passlib.context import CryptContext

from .database import db
from .model_types import ChoiceType

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

association_table = db.Table(
    "users_chats",
    db.Column("user_id", db.Integer, db.ForeignKey("users.id")),
    db.Column("chat_id", db.Integer, db.ForeignKey("chats.id")),
)


class User(db.Model, UserMixin):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), nullable=False, unique=True)
    password = db.Column(db.String(100), nullable=False)
    registered = db.Column(db.DateTime(), default=datetime.utcnow)
    messages = db.relationship("Message", backref="sender")

    def __init__(self, email, password):
        self.email = email
        self.password = pwd_context.hash(password)

    def __repr__(self):
        return f"{self.email}"

    def check_password(self, password):
        return pwd_context.verify(password, self.password)


class Chat(db.Model):
    __tablename__ = "chats"
    id = db.Column(db.Integer, primary_key=True)
    messages = db.relationship("Message", backref="chat")
    users = db.relationship("User", secondary=association_table, backref="chats")
    chat_type = db.Column(ChoiceType({"pm": "pm", "cn": "cn"}))

    def __init__(self, chat_type):
        self.chat_type = chat_type


class Message(db.Model):
    __tablename__ = "messages"
    id = db.Column(db.Integer, primary_key=True)
    sender_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    chat_id = db.Column(db.Integer, db.ForeignKey("chats.id"))
    text = db.Column(db.String(500), nullable=False)
    sent = db.Column(db.DateTime(), default=datetime.utcnow)

    def __init__(self, sender_id, text, chat=None):
        if chat:
            self.chat_id = chat
        self.sender_id = sender_id
        self.text = text

    def as_dict(self):
        return {
            "id": self.id,
            "text": self.text,
            "sent": str(self.sent),
            "sender": self.sender.email,
        }

src/app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired, Length, Email, EqualTo


class LoginForm(FlaskForm):
    email = StringField(label="email", validators=[DataRequired(), Email()])
    password = StringField(
        label="password", validators=[DataRequired(), Length(min=8, max=50)]
    )


class RegisterForm(FlaskForm):
    email = StringField(label="email", validators=[DataRequired(), Email()])
    password1 = StringField(
        label="password1", validators=[DataRequired(), Length(min=8, max=50)]
    )
    password2 = StringField(
        label="password2",
        validators=[DataRequired(), Length(min=8, max=50), EqualTo("password1")],
    )

src/app/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_redis import FlaskRedis
from flask_socketio import SocketIO


app = Flask(__name__)
app.config.from_object("conf.conf.Config")
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

redis_client = FlaskRedis(app)

socketio = SocketIO(app)
from .socketio import *


from .database import db

migrate = Migrate(app, db)


manager = LoginManager(app)
from app import models


from .views import *

app.register_blueprint(views.chat)


@manager.user_loader
def load_user(user_id):
    return models.User.query.get(user_id)

src/app/views.py
import json

from flask import (
    Blueprint,
    render_template,
    Response,
    redirect,
    url_for,
    session,
    make_response,
)
from flask_login import login_user, current_user
from sqlalchemy.exc import IntegrityError

from app import socketio_prefix
from app.database import db
from app.decorators import logged_in_redirect, unauthorized_redirect
from app.forms import RegisterForm, LoginForm
from app.models import User, Chat
from app import redis_client


chat = Blueprint("chat", __name__, template_folder="templates")


@chat.route("/", methods=["GET"])
@unauthorized_redirect("chat.login_page")
def index():
    # chat = Chat.query.join(User).filter(User.email.contains(current_user.email)).first()
    return render_template("index.html", current_user=current_user.email)


@chat.route("/chat", methods=["GET"])
@unauthorized_redirect("chat.login_page")
def chat_page():
    chats = Chat.query.filter(User.email == current_user.email).all()
    if chats:
        for chat in chats:
            for i in range(len(chat.users)):
                if chat.users[i].email == current_user.email:
                    del chat.users[i]
                    break
    return render_template(
        "chat.html",
        chats=chats,
        current_user=current_user.email,
    )


@chat.route("/chat/<int:id>", methods=["GET"])
def get_chat(id):
    chat = (
        Chat.query.filter(Chat.id == id, User.email == current_user.email)
        .order_by("id")
        .first()
    )
    message_list = []
    if chat:
        for message in chat.messages:
            message_list.append(message.as_dict())
        return json.dumps(message_list)


@chat.route("/online", methods=["GET"])
def get_online_users():
    users_online = []
    for key in redis_client.scan_iter(f"{socketio_prefix}:*"):
        users_online.append(key.decode().split(":")[-1])
    return {"online": users_online}


@chat.route("/login", methods=["GET", "POST"])
@logged_in_redirect("chat.index")
def login_page():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        try:
            assert user.check_password(form.password.data)
            login_user(user)
            session["user"] = user.email
            resp = make_response(redirect(url_for("chat.index")))
            resp.set_cookie("user", current_user.email)
            return resp
        except (AttributeError, AssertionError):
            return Response("Invalid credentials", status=401)
    return render_template("login.html", form=form)


@chat.route("/register", methods=["GET", "POST"])
@logged_in_redirect("chat.index")
def register_page():
    form = RegisterForm()
    if form.validate_on_submit():
        try:
            db.session.add(User(email=form.email.data, password=form.password1.data))
            db.session.commit()
            return redirect(url_for("chat.index"))
        except IntegrityError as e:
            return Response("User with such email already exists", 400)
    return render_template("register.html", form=form)

src/app/templates/chat.html
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css"
          rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="static/css/chat.css">

</head>
<body>
<div class="container">
    <h3 class=" text-center">Messaging</h3>
    <div class="messaging">
        <div class="inbox_msg">
            <div class="inbox_people">
                <div class="headind_srch">
                    <div class="recent_heading">
                        <h4>Recent</h4>
                    </div>
                    <div class="srch_bar">
                        <div class="stylish-input-group">
                            <input type="text" class="search-bar" placeholder="Search">
                            <span class="input-group-addon">
                <button type="button"> <i class="fa fa-search" aria-hidden="true"></i> </button>
                </span></div>
                    </div>
                </div>
                <div class="inbox_chat">
                    {% if chats %}
                        <div class="chat_list active_chat" id={{ chats[0].id }}>
                                <div class="chat_people">
                                    <div class="chat_img"><img src="https://ptetutorials.com/images/user-profile.png"
                                                               alt="sunil"></div>
                                    <div class="chat_ib">
                                        <h5>{% for user in chats[0].users[0:2] %}{{ user.email }} {% endfor %} <span class="chat_date">{% if chats[0].messages|length > 1 %}{{ chats[0].messages[-1].sent }}{% endif %}</span></h5>
                                        <p>{% if chats[0].messages|length > 1 %}{{ chats[0].messages[-1].text }}{% endif %}</p>
                                    </div>
                                </div>
                        </div>
                    {% endif %}
                    {% for chat in chats[1:-1] %}
                        <div class="chat_list" id="{{ chat.id }}">
                            <div class="chat_people">
                                <div class="chat_img"><img src="https://ptetutorials.com/images/user-profile.png"
                                                           alt="sunil"></div>
                                <div class="chat_ib">
                                    <h5>{% for user in chat.users[0:2] %}{{ user.email }} {% endfor %} <span class="chat_date">{{ chat.messages[-1].sent }}</span></h5>
                                    <p>{{ chat.messages[-1].text }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="mesgs">
                <div class="msg_history" id="chat_history">
                    {% for message in chats[0].messages %}
                        {% if message.sender.email != current_user %}
                            <div class="incoming_msg">
                                <div class="incoming_msg_img"><img src="https://ptetutorials.com/images/user-profile.png"
                                                                   alt="sunil"></div>
                                <div class="received_msg">
                                    <div class="received_withd_msg">
                                        <p>{{ message.text }}</p>
                                        <span class="time_date">{{ message.sent }}</span></div>
                                </div>
                            </div>
                        {% else %}
                            <div class="outgoing_msg">
                                <div class="sent_msg">
                                    <p>{{ message.text }}</p>
                                    <span class="time_date">{{ message.sent }}</span></div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="type_msg">
                    <div class="input_msg_write">
                        <input type="text" class="write_msg" id="msg" placeholder="Type a message"/>
                        <button class="msg_send_btn" id="send" type="button"><i class="fa fa-paper-plane-o"
                                                                      aria-hidden="true"></i></button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<div id="online">
    <header id="online-header">Users online</header>
    <div id="users-online">
        <ul id="users-list">
            <li class="online-user"></li>
        </ul>
    </div>
</div>
<script src="https://cdn.socket.io/3.1.1/socket.io.min.js" integrity="sha384-gDaozqUvc4HTgo8iZjwth73C6dDDeOJsAgpxBcMpZYztUfjHXpzrpdrHRdVp8ySO" crossorigin="anonymous"></script>
<script src="static/js/chat.js"></script>
</body>
</html>

src/app/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="https://cdn.socket.io/3.1.1/socket.io.min.js" integrity="sha384-gDaozqUvc4HTgo8iZjwth73C6dDDeOJsAgpxBcMpZYztUfjHXpzrpdrHRdVp8ySO" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script
</head>
<body>
</body>
</html>

src/app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/css/util.css">
	<link rel="stylesheet" type="text/css" href="static/css/main.css">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
				<form class="login100-form validate-form" method="POST">
					<span class="login100-form-title p-b-33">
						Account Login
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						{{ form.email(class_="input100", type="text", placeholder="Email") }}
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

					<div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
						{{ form.password(class_="input100", type="password", placeholder="Password") }}
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

                    {{ form.csrf_token }}

					<div class="container-login100-form-btn m-t-20">
						<button class="login100-form-btn" formaction={{ url_for('chat.login_page') }}>
							Sign in
						</button>
					</div>

					<div class="text-center">
						<span class="txt1">
							Create an account?
						</span>

						<a href="{{ url_for('chat.register_page') }}" class="txt2 hov1">
							Sign up
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>



<!--===============================================================================================-->
	<script src="static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/bootstrap/js/popper.js"></script>
	<script src="static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/daterangepicker/moment.min.js"></script>
	<script src="static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="static/js/main.js"></script>

</body>
</html>

src/app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Sign up</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/css/util.css">
	<link rel="stylesheet" type="text/css" href="static/css/main.css">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
				<form class="login100-form validate-form" method="POST">
					<span class="login100-form-title p-b-33">
						Register
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">

                        {{ form.email(class_="input100", type="text", placeholder="Email") }}
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

					<div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
						{{ form.password1(class_="input100", type="password", placeholder="Password") }}
                        <span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

                    <div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
                        {{ form.password2(class_="input100", type="password", placeholder="Repeat password") }}
                        <span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

                    {{ form.csrf_token }}

					<div class="container-login100-form-btn m-t-20">
						<button class="login100-form-btn" formaction={{ url_for('chat.register_page') }}>
							Sign up!
						</button>
					</div>

                    <div class="text-center">
						<span class="txt1">
							Have an account?
						</span>

						<a href="{{ url_for('chat.login_page') }}" class="txt2 hov1">
							Sign in
						</a>
					</div>

				</form>
			</div>
		</div>
	</div>



<!--===============================================================================================-->
	<script src="static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/bootstrap/js/popper.js"></script>
	<script src="static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/daterangepicker/moment.min.js"></script>
	<script src="static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="static/js/main.js"></script>

</body>
</html>